repos:

- repo: local
  hooks:
  - id: unasync-rewrite
    name: unasync-rewrite
    entry: python .unasync-rewrite.py
    language: python
    types: [python]
    files: ^(ahk/_async/.*\.py|\.unasync-rewrite\.py|tests/_async/.*\.py)
    pass_filenames: false
    additional_dependencies:
        - unasync
        - tokenize_rt
        - black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: mixed-line-ending
        args: ["-f", "lf"]
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
-   repo: https://github.com/psf/black
    rev: '22.12.0'
    hooks:
    -   id: black
        args:
            - "-S"
            - "-l"
            - "120"
        exclude: ^(ahk/_sync/.*\.py)
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
    -   id: mypy
        args:
            - "--strict"
        exclude: ^(tests/.*|setup\.py|\.build\.py|\.unasync-rewrite\.py|_tests_setup\.py|buildunasync\.py)
        additional_dependencies:
          - jinja2

-   repo: https://github.com/pycqa/flake8
    rev: '6.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        args:
          - "--ignore"
          - "E501,E704,E301,W503"
        files: ahk\/(?!_sync).*
